---
- :label: Catalogos
  :items:
  - :label: Socios de Negocios
    :url: business_partners_path
  - :label: Bodegas
    :url: storehouses_path
  # - :label: Asignaturas
  #   :url: admin_subjects_path
  # - :label: Grupos
  #   :url: admin_groups_path
  # - :label: Intervalos
  #   :url: admin_intervals_path
  # - :label: Niveles
  #   :url: admin_levels_path
